name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          # Add commands to install dependencies and build your project here
          npm ci
          npm run build

      - name: Debug build output
        run: |
          echo "Current working directory: $(pwd)"
          ls -al /home/runner/work/beginner-devops-project-static-website-code/beginner-devops-project-static-website-code/build
         # ls -al /github/workspace
         # ls -al /github/workspace/build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            cp -R /home/runner/work/beginner-devops-project-static-website-code/beginner-devops-project-static-website-code/build/* .
            sudo service nginx restart
