name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          # Add commands to install dependencies and build your project here
          npm ci
          npm run build

      - name: Debug build output
        run: |
          echo "Current working directory: $(pwd)"
          ls -al
          ls -al /home/runner/work/beginner-devops-project-static-website-code/beginner-devops-project-static-website-code
          ls -al /home/runner/work/beginner-devops-project-static-website-code/beginner-devops-project-static-website-code/build
    
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            ls -al
            cd /var/www/html
            ls -al
            rm -rf *
            scp -r scp -r C:\Users\linds\OneDrive\Desktop\RandoStatik\reactfolio\build\* root@64.227.12.76
            sudo service nginx restart


