name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          # Add commands to install dependencies and build your project here
          npm ci
          npm run build

      - name: Verify build output
        run: |
          ls -al /github/workspace/build
          # Add any additional commands to verify the build output here

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            cp -R /github/workspace/build/* .
            sudo service nginx restart
